---
abstract: 'parse and format IRC messages using C<String::Tagged>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  String::Tagged: '0.10'
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Tagged-IRC
provides:
  String::Tagged::IRC:
    file: lib/String/Tagged/IRC.pm
    version: '0.01'
requires:
  Convert::Color::RGB8: '0'
  Convert::Color::mIRC: '0'
  String::Tagged: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
